name: Windows Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    env:
      CI: true
      CONFIRM_DROP: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install PostgreSQL 14
        run: |
          choco install postgresql14 --force --params '/Password:postgres'
      - name: yarn, lint, build and test
        run: |
          $env:PATH += ";C:\Program Files\PostgreSQL\14\bin"
          cp .env.ci .env
          yarn --frozen-lockfile
          yarn setup
          yarn build
          yarn lint
          yarn test --ci
          yarn depcheck
